### PR TITLE
Added native plugins directly to the project

### PR DESCRIPTION
**Pull request by noxer**
Step 2 of the (original) readme explains that due to naming conflicts, the native plugins for only one of the architectures can be added at the same time. The naming conflict is in the file `HoloLensForCV.winmd` which just contains API information shared by both plugins. Moving it to the `Plugins` folder and removing the copy from each of the architecture folders solves this problem. The DLLs can be marked for their respective architecture.

The project can now be built for both HoloLens1 (x86) and HoloLens2 (ARM) at the same time.

Cheers, Tim

PS: It would be nice if you could add the `hacktoberfest-accepted` label, so this PR counts towards my progress. Thanks.

### CODE REVIEW

**Comment by doughtmw** [comment]
Hi @noxer! Thanks for your contribution. Are you testing this project with a HoloLens 1 or HoloLens 2? I'm having some difficulty running the ARM sample for the HL2 with your fork. Using the master branch, I was able to merge all of the plugins into Unity and set their individual properties to allow for building and deploying to both the HL1 & HL2 from the same project.

**Comment by noxer** [comment]
Let me investigate, maybe I forgot a file...

**Comment by noxer** [comment]
The .gitignore excluded the ARM folder so it was not included in the commit. I'm sorry for that. Testing it now.

**Comment by noxer** [comment]
Now it works!

**Pull request merged**
